[package]
name = "credible-coin"
version = "0.1.0"
edition = "2021"
description = "A zero-knowledge proof system to asses cryptocurrency exchange solvency."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 =  {version = "0.26.0", features = ["rand"]}
rand = "0.8.5"
sha2 = "0.10.6"
num = "0.4.0"
rs_merkle = "1.3.0"
# TEMP Dependency
polars = "0.27.2"