# Here provide the path to emp_zk or emp_complete's test directory
# so that we can copy over the generated c++ file to that directory
# and it can work properly when we run "make install". Make sure to 
# include the full path so if it is in the bool directory in emp be
# sure to specify that

# NOTE: Make sure to copy this file and make a new configuration
# file in the same directory as this sample (it must be named credible_config.yaml)
# The credible_config.yaml should also be added to the .gitignore file (if not yet added)
emp_path: "/path/to/emp/test/folder"